version: 2
jobs:
  build:
    docker:
      - image: quay.io/turner/harbor-cicd-image:v0.17.0
    environment:
      - FILE: .circleci/docker-compose.yml
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Set image version/tag (e.g., 1.1.0 for master, 1.1.0-develop.42 for other)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "VERSION=$(jq -r .version < package.json)" > .env
            else
              echo "VERSION=$(jq -r .version < package.json)-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}" > .env
            fi
      - run:
          name: Build app image
          command: docker-compose -f "${FILE}" build
      - run:
          name: Login to registry
          command: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASS}" quay.io
      - run:
          name: Push app image to registry
          command: docker-compose -f "${FILE}" push
      - run:
          name: Catalog in Harbor
          command: harbor-compose -f "${FILE}" catalog
      - run:
          name: Deploy to Harbor
          command: harbor-compose -f "${FILE}" deploy
